### ISSUE TITLE
Pass Resource ID in data()

### ISSUE THREAD

**Issue by mikecornille** [cloudstudio/nova-card-extended#1]
I was hoping you could help me with passing the resource ID into my DB query.

`(new CardExtended())
            ->view('cards.text')
            ->data(\App\Invoice::find($request->resourceId))
            ->onlyOnDetail()
            ->width('full'),`

I tried $request->resourceId and $this->id, but I can't get the current resource id, do you know how I can access it?  Thanks!

**Comment by cloudstudio** [comment]
Hello @mikecornille I think you can't pass id by default.

You can do something like this : 

```
$explodeUrl = explode('/', strrev($_SERVER['HTTP_REFERER']), 2);
return strrev($explodeUrl[0]);
```

**Comment by mikecornille** [comment]
Thank You!
